version: 2.1
jobs:
    build:
        docker:
            - image: cimg/base:2022.05
    
        steps:
            - run:
                name: "Build Docker Image"
                command: docker build -t hyunha/docker-react-app -f Dockerfile.dev .
            
            - run:
                name: "Run Tests"
                command: docker run -e CI=true hyunha/docker-react-app npm run test -- --coverage
            
workflows:
    version: 2
    build-and-test:
        jobs:
            - build
