version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:lts
    
        steps:
            - checkout
            - setup_remote_docker
            
            - run:
                name: "PWD"
                command: pwd
            - run:
                name: "ls"
                command: ls

            - run:
                name: "Build Docker Image"
                command: docker build -t hyunha/docker-react-app -f Dockerfile.dev ../
            
            - run:
                name: "Run Tests"
                command: docker run -e CI=true hyunha/docker-react-app npm run test -- --coverage
            
workflows:
    build-and-test:
        jobs:
            - build
